.PHONY: sim clean

sim:
	$(MAKE) -C ej1 sim
	$(MAKE) -C ej2 sim
	$(MAKE) -C ej3 sim
	$(MAKE) -C ej4 sim
	$(MAKE) -C ej5 sim
	$(MAKE) -C ej6 sim
	$(MAKE) -C ej7 sim
	$(MAKE) -C ej8 sim
	$(MAKE) -C ej9 sim

clean:
	$(MAKE) -C ej1 clean
	$(MAKE) -C ej2 clean
	$(MAKE) -C ej3 clean
	$(MAKE) -C ej4 clean
	$(MAKE) -C ej5 clean
	$(MAKE) -C ej6 clean
	$(MAKE) -C ej7 clean
	$(MAKE) -C ej8 clean
	$(MAKE) -C ej9 clean
