TB = flags_ej6_tb
SRCS = sumador_simple.sv sumador_completo.sv sumador_4b.sv overflow_4b.sv negativo_4b.sv zero_4b.sv sumador_flags_4b.sv flags_ej6_tb.sv
PRE_SRCS = ../ej2/overflow_4b.sv ../ej4/negativo_4b.sv ../ej5/zero_4b.sv
LIB = ../lib
include $(LIB)/sim.mk
