.PHONY: sim clean

sim:
	$(MAKE) -C ej1 sim
	$(MAKE) -C ej2 sim
	$(MAKE) -C ej3 sim
	$(MAKE) -C ej4 sim
	$(MAKE) -C ej5 sim

clean:
	$(MAKE) -C ej1 clean
	$(MAKE) -C ej2 clean
	$(MAKE) -C ej3 clean
	$(MAKE) -C ej4 clean
	$(MAKE) -C ej5 clean
