TB = sumador_restador_4b_tb
PRE_SRCS = ../ej1/sumador_simple.sv ../ej2/sumador_completo.sv ../ej3/sumador_4b.sv \
           ../ej4/restador_simple.sv ../ej5/restador_completo.sv ../ej6/restador_4b.sv
SRCS = sumador_simple.sv sumador_completo.sv sumador_4b.sv \
       restador_simple.sv restador_completo.sv restador_4b.sv \
       sumador_restador_4b.sv sumador_restador_4b_tb.sv
include ../lib/sim.mk
