TB = datapath_sumador_tb
PRE_SRCS = ../ej1/ff_d.sv ../ej2/registro_1b.sv ../ej3/registro_4b.sv \
           ../lib/sumador_simple.sv ../lib/sumador_completo.sv ../lib/sumador_4b.sv
SRCS = ff_d.sv registro_1b.sv registro_4b.sv \
       sumador_simple.sv sumador_completo.sv sumador_4b.sv \
       datapath_sumador.sv datapath_sumador_tb.sv
include ../lib/sim.mk
