TB = uupal_tb
PRE_SRCS = ../ej1/and_4b.sv ../ej2/or_4b.sv \
           ../ej3/sumador_simple.sv ../ej3/sumador_completo.sv ../ej3/sumador_4b.sv \
           ../ej4/restador_simple.sv ../ej4/restador_completo.sv ../ej4/restador_4b.sv
SRCS = ff_d.sv registro_1b.sv registro_4b.sv and_4b.sv or_4b.sv \
       sumador_simple.sv sumador_completo.sv sumador_4b.sv \
       restador_simple.sv restador_completo.sv restador_4b.sv uupal.sv uupal_tb.sv
include ../lib/sim.mk

